const menu=document.querySelector('#mobileMenu'),menuBtn=document.querySelector('#menuBtn');
function closeMenu(){menu.hidden=true;menuBtn.setAttribute('aria-expanded','false');menuBtn.setAttribute('aria-label','開啟選單');}
menuBtn.addEventListener('click',()=>{const open=menu.hidden;menu.hidden=!open;menuBtn.setAttribute('aria-expanded',String(open));menuBtn.setAttribute('aria-label',open?'關閉選單':'開啟選單');});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!menu.hidden){closeMenu();menuBtn.focus();}});
window.addEventListener('resize',()=>{if(innerWidth>1024)closeMenu();});
const reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const target=document.getElementById(a.hash.slice(1));if(!target)return;e.preventDefault();closeMenu();target.setAttribute('tabindex','-1');target.focus({preventScroll:true});target.scrollIntoView({behavior:reduced()?'instant':'smooth'});history.replaceState(null,'',a.hash);}));
const scenarios={a:['仍持有：先看時間與對象','假設父親於死亡前一年贈與股票給子女，且子女仍持有。','關鍵：在 2 年內且屬列舉對象，須依規定併計；股票價值另依估價規則確認。'],b:['已出售：仍要檢查贈與紀錄','假設父親於死亡前一年贈與股票給子女，子女已在父親死亡前出售。','關鍵：出售不當然排除併計；不要直接用出售價代替法定估價。'],c:['條件不明：先補資料','若不清楚移轉日期、是否為贈與，或受贈人身分，就無法僅憑股票交易紀錄下結論。','關鍵：先找出移轉文件及親屬關係，向國稅局確認適用。']};
const tabs=[...document.querySelectorAll('[role=tab]')],panel=document.querySelector('#scenarioPanel');
function render(key){tabs.forEach(t=>{const selected=t.dataset.scenario===key;t.setAttribute('aria-selected',String(selected));t.tabIndex=selected?0:-1;});panel.setAttribute('aria-labelledby','tab-'+key);const s=scenarios[key];panel.replaceChildren();for(const [tag,text,cls] of [['h3',s[0],''],['p',s[1],''],['p',s[2],'key']]){const el=document.createElement(tag);el.textContent=text;el.className=cls;panel.append(el);}const a=document.createElement('a');a.className='citation';a.href=key==='b'?'https://www.etax.nat.gov.tw/etwmain/tax-info/understanding/tax-q-and-a/national/estate-tax/calculation/aKr7z93':'https://law-out.mof.gov.tw/LawContent.aspx?id=FL006067';a.textContent='核對官方依據 ↗';a.target='_blank';a.rel='noopener';panel.append(a);document.querySelector('#scenarioStatus').textContent='目前選擇：'+tabs.find(t=>t.dataset.scenario===key).textContent;}
tabs.forEach((t,i)=>{t.addEventListener('click',()=>render(t.dataset.scenario));t.addEventListener('keydown',e=>{let n;if(e.key==='ArrowRight')n=(i+1)%tabs.length;if(e.key==='ArrowLeft')n=(i+tabs.length-1)%tabs.length;if(e.key==='Home')n=0;if(e.key==='End')n=tabs.length-1;if(n!==undefined){e.preventDefault();tabs[n].focus();render(tabs[n].dataset.scenario);}});});render('a');
const checks=[...document.querySelectorAll('#checklist input')];function updateChecks(){document.querySelector('#checkStatus').textContent=`已整理 ${checks.filter(c=>c.checked).length} / ${checks.length} 項`;}
checks.forEach(c=>c.addEventListener('change',updateChecks));document.querySelector('#resetChecklist').addEventListener('click',()=>{checks.forEach(c=>c.checked=false);updateChecks();});
const back=document.querySelector('#backTop');function progress(){const max=document.documentElement.scrollHeight-innerHeight;document.querySelector('#progressBar').style.width=(max>0?Math.min(100,Math.max(0,scrollY/max*100)):0)+'%';back.classList.toggle('show',scrollY>400);back.tabIndex=scrollY>400?0:-1;}
window.addEventListener('scroll',progress,{passive:true});window.addEventListener('resize',progress);document.querySelectorAll('details').forEach(d=>d.addEventListener('toggle',progress));back.addEventListener('click',()=>{window.scrollTo({top:0,behavior:reduced()?'instant':'smooth'});document.querySelector('.brand').focus({preventScroll:true});});progress();
